#security:
#  oauth2:
#    resource:
#      jwt:
#        key-uri: http://auth.security.liuyuefeng.org:9090/oauth/token_key
#    client:
#      client-id: priceService
#      client-secret: 123456spring:
spring:
  application:
    name: price-api
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719